### ISSUE TITLE
无法注册和订购新套餐

### ISSUE THREAD

**Issue by xxxxjn** [qianglie/domain#7]

**Comment by sunshe35** [comment]
我也是这样子

**Comment by xxxxjn** [comment]
> 我也是这样子

但是服务没关闭没跑路，这就很迷

**Comment by athtamis** [comment]
续费以后原token失效，要重置才行。
但是月结日好像也变了，到套餐开通日流量并没有刷新

**Comment by vokuic** [comment]
扣费成功但原来的服务被关闭了，导致无法上网，钱也不打算要回来了。
重点是：有没有其他类似的良心网站可以买套餐啊？求推荐。

**Comment by JcEve** [comment]
> 扣费成功但原来的服务被关闭了，导致无法上网，钱也不打算要回来了。
> 重点是：有没有其他类似的良心网站可以买套餐啊？求推荐。
这个墙裂我三月份用到现在，虽然中间偶尔几次大姨妈，但也是能用，这次这么久都不能用了太难受了。推荐一下这个，9.9的速度也很快https://jike0.com/auth/register?code=4gan
